apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: pulsar-consumer-image
  namespace: kpack
spec:
  tag: index.docker.io/yuwsung1/pulsar-python-consumer
  serviceAccountName: kpack-sa
  builder:
    name: python-builder
    kind: Builder
  source:
    git:
      url: https://github.com/yuweisung/pulsar-python
      revision: kpack
    subPath: "consumer-bp"
